language: r
cache: packages

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - testthat
  - nlme
  - lme4
  - arm
  - coda
  - MASS

warnings_are_errors: true

script: 
  - "cd .."
  - "R CMD build rr"
  - "R CMD INSTALL rr_1.3.tar.gz"
  - "R CMD CHECK rr_1.3.tar.gz"
  - "Rscript -e 'library(devtools); test()'"

notifications:
  email:
    on_success: change
    on_failure: change
