# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

script: "Rscript -e 'library(devtools); check(args = "--as-cran"); test()'"

notifications:
  email:
    on_success: change
    on_failure: change
