language: r

env:
 global:
   - CRAN: http://cran.rstudio.com

warnings_are_errors: true

script: "Rscript -e 'library(devtools); install_deps(pkg = ".", dependencies = TRUE); check(); test()'"

notifications:
  email:
    on_success: change
    on_failure: change